# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e . -r requirements/test.txt coveralls
before_script: flake8 kibitzr_email tests
script: coverage run --source=kibitzr_email setup.py test
after_success:
  coveralls
